/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */

declare module "sst" {
  export interface Resource {
    "Api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "NoReplyEmail": {
      "configSet": string
      "sender": string
      "type": "sst.aws.Email"
    }
    "OrderEventBus": {
      "arn": string
      "name": string
      "type": "sst.aws.Bus"
    }
    "StaticSite": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
    "StripeApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Table": {
      "name": string
      "type": "sst.aws.Dynamo"
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}